#!/bin/bash

mkdir ../test

mv test.spec.cjs ../test
mv test.spec.mjs ../test

rm -r test
rm ChaiFunctions.code-workspace
rm start

echo '1. delete extensions if you are not using them'
echo '2. un-comment the desired statements in .gitignore'

cd ..
npm i mocha chai --save-dev